# Generated by Django 5.0.4 on 2024-06-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('recruiterid', models.AutoField(primary_key=True, serialize=False)),
                ('recruitername', models.CharField(max_length=225)),
                ('locatedin', models.CharField(choices=[('Saudia Arabia', 'Saudia Arabia'), ('Qatar', 'Qatar'), ('Oman', 'Oman'), ('United Arab Emirates', 'United Arab Emirates'), ('Bahrian', 'Bahrian'), ('Kuwait', 'Kuwait'), ('Egypt', 'Egypt')], max_length=100)),
                ('descrp', models.CharField(max_length=225)),
                ('businessfield', models.CharField(max_length=200)),
                ('createdby', models.CharField(max_length=50)),
                ('createddate', models.DateField()),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='jobcode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='latestupdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='updatedby',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='companyfield',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='createdby',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='createddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='placeofwork',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='recruiterid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='jobs.recruiters'),
        ),
    ]
