# Generated by Django 5.0.4 on 2024-06-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_recruiters_jobs_jobcode_jobs_latestupdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='latestupdate',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='updatedby',
        ),
        migrations.RemoveField(
            model_name='recruiters',
            name='createdby',
        ),
    ]
