# Generated by Django 5.0.4 on 2024-06-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobs_createdby_remove_jobs_latestupdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiters',
            options={'verbose_name': 'Recruiter', 'verbose_name_plural': 'Recruiters List'},
        ),
    ]
