# Generated by Django 5.0.4 on 2024-06-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_recruiters_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiters',
            name='descrp',
        ),
        migrations.AddField(
            model_name='recruiters',
            name='description',
            field=models.CharField(max_length=225, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='createddate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(default='D', null=True),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='businessfield',
            field=models.CharField(max_length=200, verbose_name='Business Field'),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='createddate',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='locatedin',
            field=models.CharField(choices=[('Saudia Arabia', 'Saudia Arabia'), ('Qatar', 'Qatar'), ('Oman', 'Oman'), ('United Arab Emirates', 'United Arab Emirates'), ('Bahrian', 'Bahrian'), ('Kuwait', 'Kuwait'), ('Egypt', 'Egypt')], max_length=100, verbose_name='Country Located'),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='recruiterid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Recruiter ID'),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='recruitername',
            field=models.CharField(max_length=225, verbose_name='Recruiter Name'),
        ),
    ]
