# Generated by Django 5.0.4 on 2024-06-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_recruiters_descrp_recruiters_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiters',
            name='isactive',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
