# Generated by Django 5.0.4 on 2024-06-18 13:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_recruiters_isactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs List'},
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='companyfield',
        ),
        migrations.AddField(
            model_name='jobs',
            name='validdate',
            field=models.DateField(null=True, verbose_name='Valid Till'),
        ),
        migrations.AddField(
            model_name='recruiters',
            name='contactperson',
            field=models.CharField(max_length=225, null=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='recruiters',
            name='email',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='recruiters',
            name='recruiterlogo',
            field=models.ImageField(null=True, upload_to='recruiter/logo/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='recruiters',
            name='telephone',
            field=models.CharField(default=0, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', 'Enter a valid telephone number.')]),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='contracttype',
            field=models.CharField(blank=True, choices=[('P', 'Permananet'), ('C', 'Contract')], max_length=1, null=True, verbose_name='Contract type'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(default='D', null=True, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='eductiondegree',
            field=models.CharField(max_length=225, verbose_name='Eductaion'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='experienceyears',
            field=models.IntegerField(verbose_name='Number of Experince'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender required'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobcode',
            field=models.CharField(max_length=100, null=True, verbose_name='Job Code'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobfield',
            field=models.CharField(max_length=225, verbose_name='Job Field'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='nationality',
            field=models.CharField(max_length=225, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='placeofwork',
            field=models.CharField(max_length=225, null=True, verbose_name='Job Location'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='recruiterid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='jobs.recruiters', verbose_name='Recruiter Name'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.FileField(null=True, upload_to='applicant/cvs/%y/%m/%d', verbose_name='Expeceted Salary'),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='description',
            field=models.TextField(max_length=225, null=True, verbose_name='Description'),
        ),
    ]
