# Generated by Django 5.0.4 on 2024-06-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobs_options_remove_jobs_companyfield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='nationality',
            field=models.CharField(choices=[('Saudia Arabia', 'Saudia Arabia'), ('Qatar', 'Qatar'), ('Oman', 'Oman'), ('United Arab Emirates', 'United Arab Emirates'), ('Bahrian', 'Bahrian'), ('Kuwait', 'Kuwait'), ('Egypt', 'Egypt')], max_length=225, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.IntegerField(null=True, verbose_name='Expeceted Salary'),
        ),
        migrations.AlterField(
            model_name='recruiters',
            name='recruiterlogo',
            field=models.ImageField(null=True, upload_to='recruiter/logo/%y/%m/%d', verbose_name='Logo'),
        ),
    ]
