# Generated by Django 5.0.4 on 2024-06-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobs_nationality_alter_jobs_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.CharField(max_length=225, null=True, verbose_name='Expeceted Salary'),
        ),
    ]
