# Generated by Django 5.0.4 on 2024-06-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_jobs_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='contracttype',
            field=models.CharField(blank=True, choices=[('Freelance', 'Freelance'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Temporary', 'Temporary')], max_length=100, null=True, verbose_name='Contract type'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Gender required'),
        ),
    ]
