# Generated by Django 5.0.4 on 2024-06-17 10:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicantID', models.AutoField(primary_key=True, serialize=False, verbose_name='Applicant ID')),
                ('fullName', models.CharField(max_length=255, verbose_name='Applicant Name')),
                ('email', models.CharField(max_length=155, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('mobile', models.CharField(default=0, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', 'Enter a valid mobile number.')])),
                ('cvFile', models.FileField(null=True, upload_to='applicant/cvs/%y/%m/%d')),
                ('password', models.CharField(max_length=225)),
                ('createddate', models.DateField()),
                ('lastlogin', models.DateTimeField()),
                ('addedby', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantOnJobs',
            fields=[
                ('incrID', models.AutoField(primary_key=True, serialize=False)),
                ('applydate', models.DateTimeField()),
                ('isview', models.BooleanField()),
                ('isfit', models.BooleanField()),
                ('viewdate', models.DateTimeField()),
                ('fitdate', models.DateTimeField()),
                ('applicantID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applicants.applicant')),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs')),
            ],
        ),
    ]
