# Generated by Django 5.0.4 on 2024-06-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_remove_applicant_addedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='createddate',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='applicantonjobs',
            name='applydate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Apply Date'),
        ),
    ]
