# Generated by Django 5.0.4 on 2024-06-18 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_alter_applicant_createddate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Applicant', 'verbose_name_plural': 'Applicants List'},
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cvFile',
            field=models.FileField(null=True, upload_to='applicant/cvs/%y/%m/%d', verbose_name='Upload CV'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.CharField(max_length=155, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='mobile',
            field=models.CharField(default=0, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', 'Enter a valid mobile number.')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='password',
            field=models.CharField(max_length=225, verbose_name='Password'),
        ),
    ]
