# Generated by Django 5.0.4 on 2024-06-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_alter_applicant_options_alter_applicant_cvfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantonjobs',
            name='fitdate',
        ),
        migrations.RemoveField(
            model_name='applicantonjobs',
            name='viewdate',
        ),
    ]
