# Generated by Django 5.0.4 on 2024-06-18 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_alter_applicantonjobs_options'),
        ('jobs', '0008_alter_jobs_nationality_alter_jobs_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantonjobs',
            name='isview',
        ),
        migrations.AlterField(
            model_name='applicantonjobs',
            name='applicantID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applicants.applicant', verbose_name='Applicant Name'),
        ),
        migrations.AlterField(
            model_name='applicantonjobs',
            name='isfit',
            field=models.BooleanField(verbose_name='Is fit or no?'),
        ),
        migrations.AlterField(
            model_name='applicantonjobs',
            name='jobid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs', verbose_name='Job Code'),
        ),
    ]
