# Generated by Django 5.0.4 on 2024-06-20 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0009_alter_applicant_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantonjobs',
            name='applicantID',
        ),
        migrations.AddField(
            model_name='applicantonjobs',
            name='cvFile',
            field=models.FileField(null=True, upload_to='applicant/cvs/%y/%m/%d', verbose_name='Upload CV'),
        ),
        migrations.AddField(
            model_name='applicantonjobs',
            name='email',
            field=models.CharField(max_length=155, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='applicantonjobs',
            name='fullName',
            field=models.CharField(max_length=255, null=True, verbose_name='Applicant Name'),
        ),
        migrations.AddField(
            model_name='applicantonjobs',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='applicantonjobs',
            name='mobile',
            field=models.CharField(default=0, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', 'Enter a valid mobile number.')], verbose_name='Mobile Number'),
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
