# Generated by Django 5.0.4 on 2024-06-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0011_applicantonjobs_coverletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantonjobs',
            name='isfit',
            field=models.BooleanField(null=True, verbose_name='Is fit or no?'),
        ),
    ]
