# Generated by Django 5.0.4 on 2024-06-20 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0012_alter_applicantonjobs_isfit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantonjobs',
            name='mobile',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', 'Enter a valid mobile number.')], verbose_name='Mobile Number'),
        ),
    ]
