# Generated by Django 5.0.4 on 2024-06-22 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0014_subscribers_createddate_subscribers_isactive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='createddate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Subcribe Date'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.CharField(max_length=155, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='inactivateddate',
            field=models.DateField(blank=True, null=True, verbose_name='Inactivation Date'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='isactive',
            field=models.BooleanField(default=True, verbose_name='Active Or Not'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='subscriberid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Subscription ID'),
        ),
    ]
